// satoshi-quotes
import dotenv from 'dotenv';
dotenv.config();

import { SimplePool, nip19, getEventHash, getSignature, getPublicKey } from 'nostr-tools';
import 'websocket-polyfill';

// Load private key from .env
const NSEC_KEY = process.env.NSEC_KEY;

if (!NSEC_KEY) {
  throw new Error("NSEC_KEY is missing from .env file");
}

// Decode key and init
const privateKey = nip19.decode(NSEC_KEY).data;
const publicKey = getPublicKey(privateKey);

// Relay config
const RELAYS = [
  'wss://relay.damus.io',
  'wss://relay.nostr.band',
  'wss://nos.lol',
  'wss://relay.snort.social'
];

const pool = new SimplePool();

// DOWN SIMPLE CODE "UP IT CRITCAL"


// Quote database
const BIBLE_QUOTES = [
  "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.\n\n— John 3:16",
  "Trust in the LORD with all your heart and lean not on your own understanding.\n\n— Proverbs 3:5",
  "I can do all things through Christ who strengthens me.\n\n— Philippians 4:13",
  "The LORD is my shepherd, I lack nothing.\n\n— Psalm 23:1",
  "Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.\n\n— Joshua 1:9",
  "But seek first his kingdom and his righteousness, and all these things will be given to you as well.\n\n— Matthew 6:33",
  "For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future.\n\n— Jeremiah 29:11",
  "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.\n\n— 1 Corinthians 13:4",
  "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.\n\n— Philippians 4:6",
  "Jesus said, 'I am the way and the truth and the life. No one comes to the Father except through me.'\n\n— John 14:6",
  "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.\n\n— 1 John 1:9",
  "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.\n\n— Romans 5:8",
  "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.\n\n— Romans 8:28",
  "For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God.\n\n— Ephesians 2:8",
  "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.\n\n— Galatians 5:22",
  "The righteous cry out, and the LORD hears them; he delivers them from all their troubles.\n\n— Psalm 34:17",
  "Come to me, all you who are weary and burdened, and I will give you rest.\n\n— Matthew 11:28",
  "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty.\n\n— Psalm 91:1",
  "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!\n\n— 2 Corinthians 5:17",
  "And my God will meet all your needs according to the riches of his glory in Christ Jesus.\n\n— Philippians 4:19",
  "But you will receive power when the Holy Spirit comes on you; and you will be my witnesses.\n\n— Acts 1:8",
  "For where two or three gather in my name, there am I with them.\n\n— Matthew 18:20",
  "Let not your hearts be troubled. Believe in God; believe also in me.\n\n— John 14:1",
  "The name of the LORD is a fortified tower; the righteous run to it and are safe.\n\n— Proverbs 18:10",
  "But those who hope in the LORD will renew their strength. They will soar on wings like eagles.\n\n— Isaiah 40:31",
  "No weapon forged against you will prevail, and you will refute every tongue that accuses you.\n\n— Isaiah 54:17",
  "Dear friends, let us love one another, for love comes from God. Everyone who loves has been born of God and knows God.\n\n— 1 John 4:7",
  "Humble yourselves before the Lord, and he will lift you up.\n\n— James 4:10",
  "The fear of the LORD is the beginning of wisdom, and knowledge of the Holy One is understanding.\n\n— Proverbs 9:10",
  "Yet to all who did receive him, to those who believed in his name, he gave the right to become children of God.\n\n— John 1:12",
  "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.\n\n— Romans 6:23",
  "And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus.\n\n— Colossians 3:17",
  "Rejoice always, pray continually, give thanks in all circumstances; for this is God’s will for you in Christ Jesus.\n\n— 1 Thessalonians 5:16-18",
  "Cast your cares on the LORD and he will sustain you; he will never let the righteous be shaken.\n\n— Psalm 55:22",
  "The LORD will fight for you; you need only to be still.\n\n— Exodus 14:14",
  "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.\n\n— Galatians 6:9",
  "For no word from God will ever fail.\n\n— Luke 1:37",
  "But you, LORD, are a shield around me, my glory, the One who lifts my head high.\n\n— Psalm 3:3",
  "The LORD is my light and my salvation—whom shall I fear? The LORD is the stronghold of my life—of whom shall I be afraid?\n\n— Psalm 27:1",
  "Take delight in the LORD, and he will give you the desires of your heart.\n\n— Psalm 37:4",
  "He heals the brokenhearted and binds up their wounds.\n\n— Psalm 147:3",
  "The LORD is close to the brokenhearted and saves those who are crushed in spirit.\n\n— Psalm 34:18",
  "A new command I give you: Love one another. As I have loved you, so you must love one another.\n\n— John 13:34",
  "Greater love has no one than this: to lay down one’s life for one’s friends.\n\n— John 15:13",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "And so we know and rely on the love God has for us. God is love. Whoever lives in love lives in God, and God in them.\n\n— 1 John 4:16",
  "Get rid of all bitterness, rage and anger, brawling and slander, along with every form of malice.\n\n— Ephesians 4:31",
  "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.\n\n— Ephesians 4:32",
  "If we claim to be without sin, we deceive ourselves and the truth is not in us.\n\n— 1 John 1:8",
  "Whoever conceals their sins does not prosper, but the one who confesses and renounces them finds mercy.\n\n— Proverbs 28:13",
  "The LORD is my strength and my shield; my heart trusts in him, and he helps me.\n\n— Psalm 28:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "Commit to the LORD whatever you do, and he will establish your plans.\n\n— Proverbs 16:3",
  "For the word of God is alive and active. Sharper than any double-edged sword.\n\n— Hebrews 4:12",
  "But the Lord is faithful, and he will strengthen you and protect you from the evil one.\n\n— 2 Thessalonians 3:3",
  "The LORD is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge.\n\n— Psalm 18:2",
  "But you, LORD, are a compassionate and gracious God, slow to anger, abounding in love and faithfulness.\n\n— Psalm 86:15",
  "The LORD is gracious and righteous; our God is full of compassion.\n\n— Psalm 116:5",
  "He gives strength to the weary and increases the power of the weak.\n\n— Isaiah 40:29",
  "The LORD is near to all who call on him, to all who call on him in truth.\n\n— Psalm 145:18",
  "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers.\n\n— Romans 8:38",
  "The LORD makes firm the steps of the one who delights in him.\n\n— Psalm 37:23",
  "Blessed are those who hunger and thirst for righteousness, for they will be filled.\n\n— Matthew 5:6",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "I have hidden your word in my heart that I might not sin against you.\n\n— Psalm 119:11",
  "Peace I leave with you; my peace I give you. I do not give to you as the world gives.\n\n— John 14:27",
  "The LORD bless you and keep you; the LORD make his face shine on you and be gracious to you.\n\n— Numbers 6:24-25",
  "Let everything that has breath praise the LORD. Praise the LORD.\n\n— Psalm 150:6",
  "The LORD is righteous in all his ways and faithful in all he does.\n\n— Psalm 145:17",
  "I am the resurrection and the life. The one who believes in me will live, even though they die.\n\n— John 11:25",
  "The fear of the LORD leads to life; then one rests content, untouched by trouble.\n\n— Proverbs 19:23",
  "But he was pierced for our transgressions, he was crushed for our iniquities.\n\n— Isaiah 53:5",
  "My grace is sufficient for you, for my power is made perfect in weakness.\n\n— 2 Corinthians 12:9",
  "The LORD your God is with you, the Mighty Warrior who saves.\n\n— Zephaniah 3:17",
  "Whoever believes in the Son has eternal life, but whoever rejects the Son will not see life.\n\n— John 3:36",
  "The LORD is slow to anger, abounding in love and forgiving sin and rebellion.\n\n— Numbers 14:18",
  "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.\n\n— Psalm 32:8",
  "For we walk by faith, not by sight.\n\n— 2 Corinthians 5:7",
  "The LORD is good to those whose hope is in him, to the one who seeks him.\n\n— Lamentations 3:25",
  "Do not judge, and you will not be judged. Do not condemn, and you will not be condemned.\n\n— Luke 6:37",
  "The joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "He who began a good work in you will carry it on to completion until the day of Christ Jesus.\n\n— Philippians 1:6",
  "I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit.\n\n— John 15:5",
  "The LORD gives strength to his people; the LORD blesses his people with peace.\n\n— Psalm 29:11",
  "Repent, then, and turn to God, so that your sins may be wiped out.\n\n— Acts 3:19",
  "Blessed is the one whose transgressions are forgiven, whose sins are covered.\n\n— Psalm 32:1",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For everyone who asks receives; the one who seeks finds; and to the one who knocks, the door will be opened.\n\n— Matthew 7:8",
  "The LORD is faithful to all his promises and loving toward all he has made.\n\n— Psalm 145:13",
  "But if we walk in the light, as he is in the light, we have fellowship with one another.\n\n— 1 John 1:7",
  "The fear of the LORD is the beginning of knowledge, but fools despise wisdom and instruction.\n\n— Proverbs 1:7",
  "I have fought the good fight, I have finished the race, I have kept the faith.\n\n— 2 Timothy 4:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "In the same way, let your light shine before others, that they may see your good deeds.\n\n— Matthew 5:16",
  "The LORD is good and his love endures forever; his faithfulness continues through all generations.\n\n— Psalm 100:5",
  "For the eyes of the Lord are on the righteous and his ears are attentive to their prayer.\n\n— 1 Peter 3:12",
  "I will praise you, LORD, with all my heart; I will tell of all your wonderful deeds.\n\n— Psalm 9:1",
  "God is our refuge and strength, an ever-present help in trouble.\n\n— Psalm 46:1",
  "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.\n\n— Matthew 7:7",
  "The LORD is righteous; he loves justice. The upright will see his face.\n\n— Psalm 11:7",
  "I am the bread of life. Whoever comes to me will never go hungry.\n\n— John 6:35",
  "The LORD sustains the humble but casts the wicked to the ground.\n\n— Psalm 147:6",
  "For God did not send his Son into the world to condemn the world, but to save the world through him.\n\n— John 3:17",
  "The LORD is my helper; I will not be afraid. What can mere mortals do to me?\n\n— Hebrews 13:6",
  "Be joyful in hope, patient in affliction, faithful in prayer.\n\n— Romans 12:12",
  "Do everything in love.\n\n— 1 Corinthians 16:14",
  "But whoever drinks the water I give them will never thirst.\n\n— John 4:14",
  "The LORD upholds all who fall and lifts up all who are bowed down.\n\n— Psalm 145:14",
  "And now these three remain: faith, hope and love. But the greatest of these is love.\n\n— 1 Corinthians 13:13",
  "The LORD is a God of justice. Blessed are all who wait for him!\n\n— Isaiah 30:18",
  "I will never leave you nor forsake you.\n\n— Hebrews 13:5",
  "Blessed are the peacemakers, for they will be called children of God.\n\n— Matthew 5:9",
  "The LORD watches over you—the LORD is your shade at your right hand.\n\n— Psalm 121:5",
  "My soul finds rest in God; my salvation comes from him.\n\n— Psalm 62:1",
  "Whoever has the Son has life; whoever does not have the Son of God does not have life.\n\n— 1 John 5:12",
  "For the Son of Man came to seek and to save the lost.\n\n— Luke 19:10",
  "Whatever you do, work at it with all your heart, as working for the Lord.\n\n— Colossians 3:23",
  "The LORD is good to all; he has compassion on all he has made.\n\n— Psalm 145:9",
  "I am the good shepherd. The good shepherd lays down his life for the sheep.\n\n— John 10:11",
  "Blessed are those who mourn, for they will be comforted.\n\n— Matthew 5:4",
  "For everyone born of God overcomes the world. This is the victory that has overcome the world, even our faith.\n\n— 1 John 5:4",
  "Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up.\n\n— Ephesians 4:29",
  "I am the light of the world. Whoever follows me will never walk in darkness.\n\n— John 8:12",
  "But the wisdom that comes from heaven is first of all pure; then peace-loving, considerate, submissive.\n\n— James 3:17",
  "I am the Alpha and the Omega, the First and the Last, the Beginning and the End.\n\n— Revelation 22:13",
  "For the joy set before him he endured the cross, scorning its shame.\n\n— Hebrews 12:2",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "The Spirit of the Sovereign LORD is on me, because the LORD has anointed me to proclaim good news.\n\n— Isaiah 61:1",
  "I will sing to the LORD, for he has been good to me.\n\n— Psalm 13:6",
  "For the LORD loves the just and will not forsake his faithful ones.\n\n— Psalm 37:28",
  "The LORD is my strength and my defense; he has become my salvation.\n\n— Psalm 118:14",
  "Blessed are the pure in heart, for they will see God.\n\n— Matthew 5:8",
  "The LORD is my rock, my fortress and my deliverer; my God is my rock.\n\n— 2 Samuel 22:2",
  "The Spirit himself testifies with our spirit that we are God’s children.\n\n— Romans 8:16",
  "I will praise you, LORD, among the nations; I will sing of you among the peoples.\n\n— Psalm 108:3",
  "The LORD is my strength and my song; he has given me victory.\n\n— Exodus 15:2",
  "For the kingdom of God is not a matter of eating and drinking, but of righteousness, peace and joy in the Holy Spirit.\n\n— Romans 14:17",
  "The LORD is compassionate and gracious, slow to anger, abounding in love.\n\n— Psalm 103:8",
  "I am the living bread that came down from heaven. Whoever eats this bread will live forever.\n\n— John 6:51",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "For the LORD takes delight in his people; he crowns the humble with victory.\n\n— Psalm 149:4",
  "The LORD is my light and my salvation—whom shall I fear?\n\n— Psalm 27:1",
  "By this everyone will know that you are my disciples, if you love one another.\n\n— John 13:35",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For the Spirit of God has made me, and the breath of the Almighty gives me life.\n\n— Job 33:4",
  "The LORD is my rock, my fortress and my deliverer.\n\n— Psalm 18:2",
  "For God has not given us a spirit of fear, but of power and of love and of a sound mind.\n\n— 2 Timothy 1:7",
  "The LORD is good to those whose hope is in him, to the one who seeks him.\n\n— Lamentations 3:25",
  "I am the Alpha and the Omega, says the Lord God, who is, and who was, and who is to come.\n\n— Revelation 1:8",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "The Spirit of the LORD will rest on him—the Spirit of wisdom and of understanding.\n\n— Isaiah 11:2",
  "The LORD is my rock, my fortress and my deliverer; my God is my rock.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "For the LORD is good and his love endures forever; his faithfulness continues through all generations.\n\n— Psalm 100:5",
  "The LORD is my strength and my shield; my heart trusts in him.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For everyone born of God overcomes the world. This is the victory that has overcome the world, even our faith.\n\n— 1 John 5:4",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "The LORD is my rock, my fortress and my deliverer.\n\n— 2 Samuel 22:2",
  "The Spirit himself testifies with our spirit that we are God’s children.\n\n— Romans 8:16",
  "The LORD is my light and my salvation—whom shall I fear?\n\n— Psalm 27:1",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my strength and my shield; my heart trusts in him.\n\n— Psalm 28:7",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is good to those whose hope is in him, to the one who seeks him.\n\n— Lamentations 3:25",
  "I am the Alpha and the Omega, the First and the Last, the Beginning and the End.\n\n— Revelation 22:13",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "The Spirit of the LORD will rest on him—the Spirit of wisdom and of understanding.\n\n— Isaiah 11:2",
  "The LORD is my rock, my fortress and my deliverer; my God is my rock.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14",
  "The LORD is my portion; therefore I will wait for him.\n\n— Lamentations 3:24",
  "For the joy of the LORD is your strength.\n\n— Nehemiah 8:10",
  "The LORD is my strength and my shield; in him my heart trusts.\n\n— Psalm 28:7",
  "Blessed is the one who trusts in the LORD, whose confidence is in him.\n\n— Jeremiah 17:7",
  "The LORD is a refuge for the oppressed, a stronghold in times of trouble.\n\n— Psalm 9:9",
  "For the word of the LORD is right and true; he is faithful in all he does.\n\n— Psalm 33:4",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But the one who stands firm to the end will be saved.\n\n— Matthew 24:13",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Psalm 118:14",
  "For God gave us a spirit not of fear but of power and love and self-control.\n\n— 2 Timothy 1:7",
  "The LORD is my rock and my fortress and my deliverer.\n\n— Psalm 18:2",
  "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love.\n\n— Psalm 86:15",
  "The LORD is my strength and my shield; my heart trusts in him, and I am helped.\n\n— Psalm 28:7",
  "For the LORD gives wisdom; from his mouth come knowledge and understanding.\n\n— Proverbs 2:6",
  "The LORD is my light and my salvation; whom shall I fear?\n\n— Psalm 27:1",
  "But those who hope in the LORD will renew their strength.\n\n— Isaiah 40:31",
  "The LORD is my strength and my song; he has become my salvation.\n\n— Exodus 15:2",
  "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.\n\n— 2 Timothy 1:7",
  "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.\n\n— Nahum 1:7",
  "I am the good shepherd; I know my sheep and my sheep know me.\n\n— John 10:14"
];

async function publishQuote() {
  try {
    const quote = BIBLE_QUOTES[Math.floor(Math.random() * BIBLE_QUOTES.length)];
    const event = {
      kind: 1,
      created_at: Math.floor(Date.now() / 1000),
      tags: [['t', 'bible-quote'], ['t', 'christian']],
      content: quote,
      pubkey: publicKey
    };

    event.id = getEventHash(event);
    event.sig = getSignature(event, privateKey);

    await Promise.any(pool.publish(RELAYS, event));
    console.log(`[${new Date().toLocaleTimeString()}] ✅ Published: ${quote.substring(0, 40)}...`);
  } catch (error) {
    console.error(`[${new Date().toLocaleTimeString()}] ⚠️ Error: ${error.message}`);
  }
}

function startTestSchedule() {
  // Initial immediate post
  publishQuote();
  
  // Set up recurring posts every 28800 seconds (8 hours)
  const interval = setInterval(() => {
    publishQuote().catch(e => console.error('Interval error:', e));
  }, 28800 * 1000);

  // Return cleanup function
  return () => {
    clearInterval(interval);
    console.log('🛑 Stopped Bible quote interval');
  };
}

function shutdown() {
  console.log('\n🔌 Closing relays...');
  pool.close(RELAYS);
  process.exit();
}

// Initialization
console.log(`\n🔑 Public key: ${nip19.npubEncode(publicKey)}`);
console.log('📖 Bible Quote Bot is Live: Posting every 8 hours\n');
const stopSchedule = startTestSchedule();

process.on('SIGINT', () => {
  stopSchedule();
  shutdown();
});